In [ ]:
# Install required libraries
!pip install transformers datasets gdown

In [ ]:
# Clone your GitHub repository for the emotion recognition project
!git clone https://github.com/Vincent-ZHQ/CA-MSER.git

# Change directory to the cloned repository
!cd CA-MSER

In [ ]:
!pip install rust
!pip install tokenizers

In [ ]:
!pip install --upgrade pip setuptools wheel

In [ ]:
!pip install setuptools-rust

In [ ]:
!pip install tokenizers

In [ ]:
pip install transformers  # Change the version as needed

In [ ]:
!pip install torch

In [ ]:
pip install transformers

In [1]:
# Download Wav2Vec2.0 pretrained model from Hugging Face
from transformers import Wav2Vec2Model

In [ ]:
!pip install imbalanced-learn
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

In [1]:
import torch
print("Is CUDA available:", torch.cuda.is_available())
print("CUDA version:", torch.version.cuda)
features_file = '/content/drive/MyDrive/path/to/reduced_file.pkl'

Is CUDA available: True
CUDA version: 11.8


In [2]:
import sys
import os
import time
import json  # Import json for saving results

# Add the path to the directory containing train_ser.py to the Python path
sys.path.append('CA-MSER')  # Change the path if train_ser.py is in a different directory

import train_ser
from train_ser import parse_arguments
import sys
import pickle
import os
import time


repeat_kfold = 2 # to  perform 10-fold for n-times with different seed
localtime = time.localtime(time.time())
str_time = f'{str(localtime.tm_year)}-{str(localtime.tm_mon)}-{str(localtime.tm_mday)}-{str(localtime.tm_hour)}-{str(localtime.tm_min)}'

#------------PARAMETERS---------------#

features_file = 'IEMOCAP_multi.pkl'

#  leave-one-speaker-out
# val_id = ['1M','1F','2M','2F','3M','3F','4M','4F','5M','5F']
# test_id = ['1M','1F','2M','2F','3M','3F','4M','4F','5M','5F']

#  leave-one-session-out
val_id = ['1M','2M','3M','4M','5M']
test_id = ['1F','2F','3F','4F','5F']

num_epochs  = '50'
early_stop = '10'
batch_size  = '32'
lr          = '0.00001'
random_seed = 111
gpu = '1'
gpu_ids = ['0']
save_label = str_time#'0930_01'#'alexnet_pm_0704'


#Start Cross Validation
all_stat = []

for repeat in range(repeat_kfold):

    random_seed +=  (repeat*100)
    seed = str(random_seed)

    for v_id, t_id in list(zip(val_id, test_id)):

        train_ser.sys.argv      = [

                                  'train_ser.py',
                                  features_file,
                                  '--repeat_idx', str(repeat),
                                  '--val_id',v_id,
                                  '--test_id', t_id,
                                  '--gpu', gpu,
                                  '--gpu_ids', gpu_ids,
                                  '--num_epochs', num_epochs,
                                  '--early_stop', early_stop,
                                  '--batch_size', batch_size,
                                  '--lr', lr,
                                  '--seed', seed,
                                  '--save_label', save_label,#,
                                  '--pretrained'
                                  ]


        stat = train_ser.main(parse_arguments(sys.argv[1:]))
        all_stat.append(stat)
        os.remove(save_label+'.pth')

    # with open('allstat_iemocap_'+save_label+'_'+str(repeat)+'.pkl', "wb") as fout:
    #     pickle.dump(all_stat, fout)

n_total = repeat_kfold*len(val_id)
total_best_epoch, total_epoch, total_loss, total_wa, total_ua = 0, 0, 0, 0, 0

for i in range(n_total):
    print(i, ": ", all_stat[i][0], all_stat[i][1], all_stat[i][8], all_stat[i][9], all_stat[i][10])
    total_best_epoch += all_stat[i][0]
    total_epoch += all_stat[i][1]
    total_loss += float(all_stat[i][8])
    total_wa += float(all_stat[i][9])
    total_ua += float(all_stat[i][10])

print("AVERAGE:", total_best_epoch/n_total, total_epoch/n_total, total_loss/n_total, total_wa/n_total, total_ua/n_total )

print(all_stat)

****************************************

PARAMETERS:

****************************************


       ser_task: SLM
     repeat_idx: 0
         val_id: 1M
        test_id: 1F
     num_epochs: 50
     early_stop: 10
     batch_size: 32
             lr: 1e-05
    random_seed: 111
        use_gpu: 1
        gpu_ids: ['0']
     save_label: 2024-10-20-15-22
   oversampling: False
     pretrained: True
****************************************



Dataset normalized with minmax scaler
	Range before normalization: [-80.0, 3.8146973e-06]
	Range after  normalization: [0.0, 1.0]

<<DATASET>>

Val. speaker id : 1M
Test speaker id : 1F
Train data      : (8778, 1, 200, 300)
Train labels    : (8778,)
Eval. data      : (1187, 1, 200, 300)
Eval. label     : (557,)
Eval. seg labels: (1187,)
Eval. num seg   : (557,)
Test data       : (1037, 1, 200, 300)
Test label      : (528,)
Test seg labels : (1037,)
Test num seg    : (528,)


pytorch version:  2.1.1+cu118
cuda version:  11.8
cudnn version:  8700
gp

/home/stud1/.local/lib/python3.10/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/stud1/.local/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)



<< SER AlexNet Finetuning model initialized >>



/home/stud1/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py:1142: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Some weights of Wav2Vec2Model were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original1', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Ser_Model(
  (alexnet_model): SER_AlexNet(
    (features): Sequential(
      (0): Conv2d(3, 64, kernel_size=(11, 11), stride=(4, 4), padding=(2, 2))
      (1): ReLU(inplace=True)
      (2): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
      (3): Conv2d(64, 192, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
      (4): ReLU(inplace=True)
      (5): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
      (6): Conv2d(192, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (7): ReLU(inplace=True)
      (8): Conv2d(384, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (9): ReLU(inplace=True)
      (10): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (11): ReLU(inplace=True)
      (12): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    )
    (avgpool): AdaptiveAvgPool2d(output_size=(6, 6))
    (classifier): Sequential(
      (0): Dropout(p=0.5, inplace=Fa

  0%|          | 0/275 [00:00<?, ?it/s]/home/stud1/anaconda3/envs/hss/lib/python3.10/site-packages/torch/nn/modules/conv.py:456: UserWarning: Applied workaround for CuDNN issue, install nvrtc.so (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:80.)
  return F.conv2d(input, weight, bias, self.stride,
100%|██████████| 19/19 [00:02<00:00,  6.42it/s]


 ang  sad  hap  neu
  29    7   46    0
   1  112    3    0
   7   47   85    7
   1  126   65   21
True
0 0
Epoch 1  (lr = 1e-05)        Loss: 1.2563 - 1.1706 - WA: 44.34% <44.34%> - UA: 50.00% <50.00%>


100%|██████████| 19/19 [00:02<00:00,  6.40it/s]


 ang  sad  hap  neu
  38    5   25   14
   1  109    2    4
   6   32   65   43
   4   99   32   78
True
1 1
Epoch 2  (lr = 1e-05)        Loss: 1.0828 - 1.0773 - WA: 52.06% <52.06%> - UA: 55.36% <55.36%>


100%|██████████| 19/19 [00:02<00:00,  6.43it/s]


 ang  sad  hap  neu
  41    7   27    7
   2  110    1    3
   4   42   76   24
   3  114   38   58
1 2
Epoch 3  (lr = 1e-05)        Loss: 1.0341 - 1.0733 - WA: 51.17% <52.06%> - UA: 56.03% <55.36%>


100%|██████████| 19/19 [00:02<00:00,  6.41it/s]


 ang  sad  hap  neu
  54    7   16    5
   3  111    0    2
   5   34   77   30
   7   95   28   83
True
3 3
Epoch 4  (lr = 1e-05)        Loss: 0.9813 - 1.0044 - WA: 58.35% <58.35%> - UA: 63.31% <63.31%>


100%|██████████| 19/19 [00:02<00:00,  6.40it/s]


 ang  sad  hap  neu
  56    7   10    9
   3  109    0    4
   5   32   72   37
   6   92   19   96
True
4 4
Epoch 5  (lr = 1e-05)        Loss: 0.9319 - 0.9782 - WA: 59.78% <59.78%> - UA: 64.16% <64.16%>


100%|██████████| 19/19 [00:02<00:00,  6.41it/s]


 ang  sad  hap  neu
  59    6    6   11
   3  107    0    6
   5   31   68   42
   6   87   11  109
True
5 5
Epoch 6  (lr = 1e-05)        Loss: 0.8814 - 0.9691 - WA: 61.58% <61.58%> - UA: 65.49% <65.49%>


100%|██████████| 19/19 [00:02<00:00,  6.42it/s]


 ang  sad  hap  neu
  59    8    9    6
   3  107    0    6
   3   33   84   26
   6   99   19   89
5 6
Epoch 7  (lr = 1e-05)        Loss: 0.8307 - 0.9861 - WA: 60.86% <61.58%> - UA: 65.88% <65.49%>


100%|██████████| 19/19 [00:02<00:00,  6.41it/s]


 ang  sad  hap  neu
  69    5    3    5
   4  102    0   10
  14   27   67   38
  18   73   11  111
True
7 7
Epoch 8  (lr = 1e-05)        Loss: 0.7766 - 0.9505 - WA: 62.66% <62.66%> - UA: 67.52% <67.52%>


100%|██████████| 19/19 [00:02<00:00,  6.40it/s]


 ang  sad  hap  neu
  66    5    4    7
   3  107    0    6
   9   27   70   40
   8   81   19  105
7 8
Epoch 9  (lr = 1e-05)        Loss: 0.7303 - 0.9526 - WA: 62.48% <62.66%> - UA: 67.49% <67.52%>


100%|██████████| 19/19 [00:02<00:00,  6.39it/s]


 ang  sad  hap  neu
  66    5    4    7
   4  103    2    7
   8   24   81   33
   9   57   21  126
True
9 9
Epoch 10  (lr = 1e-05)        Loss: 0.6977 - 0.9374 - WA: 67.50% <67.50%> - UA: 70.98% <70.98%>


100%|██████████| 19/19 [00:02<00:00,  6.40it/s]


 ang  sad  hap  neu
  62    5    6    9
   4  101    2    9
   4   25   84   33
   3   56   22  132
True
10 10
Epoch 11  (lr = 1e-05)        Loss: 0.6535 - 0.9034 - WA: 68.04% <68.04%> - UA: 70.55% <70.55%>


100%|██████████| 19/19 [00:02<00:00,  6.39it/s]


 ang  sad  hap  neu
  62    4    8    8
   4  102    2    8
   4   21   95   26
   7   49   37  120
True
11 11
Epoch 12  (lr = 1e-05)        Loss: 0.6130 - 0.9095 - WA: 68.04% <68.04%> - UA: 71.24% <71.24%>


100%|██████████| 19/19 [00:02<00:00,  6.41it/s]


 ang  sad  hap  neu
  64    5    4    9
   4  103    2    7
   6   20   81   39
   6   62   22  123
11 12
Epoch 13  (lr = 1e-05)        Loss: 0.5888 - 0.9020 - WA: 66.61% <68.04%> - UA: 70.02% <71.24%>


100%|██████████| 19/19 [00:02<00:00,  6.40it/s]


 ang  sad  hap  neu
  54    5   15    8
   4   99    6    7
   2   19  103   22
   2   47   54  110
11 13
Epoch 14  (lr = 1e-05)        Loss: 0.5544 - 0.9771 - WA: 65.71% <68.04%> - UA: 68.35% <71.24%>


100%|██████████| 19/19 [00:02<00:00,  6.39it/s]


 ang  sad  hap  neu
  64    4    7    7
   4  101    2    9
   8   19   95   24
   8   50   40  115
11 14
Epoch 15  (lr = 1e-05)        Loss: 0.5343 - 1.0373 - WA: 67.32% <68.04%> - UA: 71.04% <71.24%>


100%|██████████| 19/19 [00:02<00:00,  6.42it/s]


 ang  sad  hap  neu
  59    5   10    8
   3  105    4    4
   1   23   93   29
   3   76   36   98
11 15
Epoch 16  (lr = 1e-05)        Loss: 0.5043 - 1.0764 - WA: 63.73% <68.04%> - UA: 68.04% <71.24%>


100%|██████████| 19/19 [00:02<00:00,  6.39it/s]


 ang  sad  hap  neu
  69    4    0    9
   4  103    1    8
  14   21   80   31
  11   56   21  125
True
16 16
Epoch 17  (lr = 1e-05)        Loss: 0.4794 - 1.1074 - WA: 67.68% <67.68%> - UA: 71.60% <71.60%>


100%|██████████| 19/19 [00:02<00:00,  6.42it/s]


 ang  sad  hap  neu
  55    7    9   11
   3  106    3    4
   2   22   97   25
   3   64   34  112
16 17
Epoch 18  (lr = 1e-05)        Loss: 0.4614 - 1.1281 - WA: 66.43% <67.68%> - UA: 69.37% <71.60%>


100%|██████████| 19/19 [00:02<00:00,  6.40it/s]


 ang  sad  hap  neu
  67    4    6    5
   4  104    3    5
   8   22  100   16
   7   69   42   95
16 18
Epoch 19  (lr = 1e-05)        Loss: 0.4369 - 1.0269 - WA: 65.71% <67.68%> - UA: 71.11% <71.60%>


100%|██████████| 19/19 [00:02<00:00,  6.42it/s]


 ang  sad  hap  neu
  58    8   10    6
   2  111    0    3
   3   32   90   21
   5   90   28   90
16 19
Epoch 20  (lr = 1e-05)        Loss: 0.4156 - 1.2277 - WA: 62.66% <67.68%> - UA: 67.58% <71.60%>


100%|██████████| 19/19 [00:02<00:00,  6.40it/s]


 ang  sad  hap  neu
  61    4    7   10
   3  100    1   12
   2   18   95   31
   4   46   26  137
True
20 20
Epoch 21  (lr = 1e-05)        Loss: 0.3794 - 1.0323 - WA: 70.56% <70.56%> - UA: 72.50% <72.50%>


100%|██████████| 19/19 [00:02<00:00,  6.42it/s]


 ang  sad  hap  neu
  64    4    4   10
   3  104    2    7
   5   17   89   35
   6   49   22  136
True
21 21
Epoch 22  (lr = 1e-05)        Loss: 0.3916 - 1.0178 - WA: 70.56% <70.56%> - UA: 73.13% <73.13%>


100%|██████████| 19/19 [00:02<00:00,  6.42it/s]


 ang  sad  hap  neu
  61    4    9    8
   3  102    3    8
   3   18   99   26
   5   45   27  136
True
22 22
Epoch 23  (lr = 1e-05)        Loss: 0.3631 - 1.1040 - WA: 71.45% <71.45%> - UA: 73.49% <73.49%>


100%|██████████| 19/19 [00:02<00:00,  6.40it/s]


 ang  sad  hap  neu
  62    4    9    7
   4  101    3    8
   4   16  104   22
   7   49   42  115
22 23
Epoch 24  (lr = 1e-05)        Loss: 0.3348 - 1.0958 - WA: 68.58% <71.45%> - UA: 71.98% <73.49%>


100%|██████████| 19/19 [00:02<00:00,  6.39it/s]


 ang  sad  hap  neu
  62    4    6   10
   3   99    2   12
   4   21   93   28
   7   47   26  133
22 24
Epoch 25  (lr = 1e-05)        Loss: 0.3304 - 1.2066 - WA: 69.48% <71.45%> - UA: 71.77% <73.49%>


100%|██████████| 19/19 [00:02<00:00,  6.40it/s]


 ang  sad  hap  neu
  68    4    2    8
   3  106    0    7
   6   26   84   30
   7   62   27  117
22 25
Epoch 26  (lr = 1e-05)        Loss: 0.3182 - 1.2283 - WA: 67.32% <71.45%> - UA: 71.69% <73.49%>


100%|██████████| 19/19 [00:02<00:00,  6.39it/s]


 ang  sad  hap  neu
  61    7   11    3
   3  108    2    3
   2   23  111   10
   5   69   50   89
22 26
Epoch 27  (lr = 1e-05)        Loss: 0.2943 - 1.3746 - WA: 66.25% <71.45%> - UA: 71.33% <73.49%>


100%|██████████| 19/19 [00:02<00:00,  6.39it/s]


 ang  sad  hap  neu
  62    3    7   10
   3  100    2   11
   6   16   92   32
   5   47   30  131
22 27
Epoch 28  (lr = 1e-05)        Loss: 0.2833 - 1.1144 - WA: 69.12% <71.45%> - UA: 71.58% <73.49%>


100%|██████████| 19/19 [00:02<00:00,  6.42it/s]


 ang  sad  hap  neu
  58    5   13    6
   3  102    3    8
   2   17  100   27
   4   54   35  120
22 28
Epoch 29  (lr = 1e-05)        Loss: 0.2703 - 1.3922 - WA: 68.22% <71.45%> - UA: 70.87% <73.49%>


100%|██████████| 19/19 [00:02<00:00,  6.39it/s]


 ang  sad  hap  neu
  62    2    6   12
   3   82    6   25
   3   10   93   40
   3   17   23  170
True
29 29
Epoch 30  (lr = 1e-05)        Loss: 0.2682 - 1.0822 - WA: 73.07% <73.07%> - UA: 72.45% <72.45%>


100%|██████████| 19/19 [00:02<00:00,  6.41it/s]


 ang  sad  hap  neu
  69    3    3    7
   4   98    3   11
   8   17   82   39
  10   35   26  142
29 30
Epoch 31  (lr = 1e-05)        Loss: 0.2636 - 1.2059 - WA: 70.20% <73.07%> - UA: 72.87% <72.45%>


100%|██████████| 19/19 [00:02<00:00,  6.40it/s]


 ang  sad  hap  neu
  66    3    8    5
   3  105    2    6
   8   15  102   21
   9   60   41  103
29 31
Epoch 32  (lr = 1e-05)        Loss: 0.2489 - 1.3398 - WA: 67.50% <73.07%> - UA: 72.31% <72.45%>


100%|██████████| 19/19 [00:02<00:00,  6.41it/s]


 ang  sad  hap  neu
  59    3   13    7
   3   86   11   16
   1    7  116   22
   3   29   59  122
29 32
Epoch 33  (lr = 1e-05)        Loss: 0.2307 - 1.3681 - WA: 68.76% <73.07%> - UA: 70.70% <72.45%>


100%|██████████| 19/19 [00:02<00:00,  6.41it/s]


 ang  sad  hap  neu
  64    5    8    5
   3   99    3   11
   6   16  104   20
   5   47   39  122
29 33
Epoch 34  (lr = 1e-05)        Loss: 0.2272 - 1.3875 - WA: 69.84% <73.07%> - UA: 72.98% <72.45%>


100%|██████████| 19/19 [00:02<00:00,  6.36it/s]


 ang  sad  hap  neu
  65    4    9    4
   3  105    3    5
  10   18   95   23
  10   58   37  108
29 34
Epoch 35  (lr = 1e-05)        Loss: 0.2210 - 1.4670 - WA: 66.97% <73.07%> - UA: 71.39% <72.45%>


100%|██████████| 19/19 [00:02<00:00,  6.41it/s]


 ang  sad  hap  neu
  62    5   12    3
   4  101    4    7
   2   14  118   12
   4   63   50   96
29 35
Epoch 36  (lr = 1e-05)        Loss: 0.2195 - 1.4816 - WA: 67.68% <73.07%> - UA: 72.14% <72.45%>


100%|██████████| 19/19 [00:02<00:00,  6.40it/s]


 ang  sad  hap  neu
  66    3    8    5
   3   92    5   16
   2   10  110   24
   6   34   42  131
True
36 36
Epoch 37  (lr = 1e-05)        Loss: 0.2072 - 1.2337 - WA: 71.63% <71.63%> - UA: 74.16% <74.16%>


100%|██████████| 19/19 [00:02<00:00,  6.40it/s]


 ang  sad  hap  neu
  65    5    7    5
   3   99    5    9
   4   19  100   23
   6   61   42  104
36 37
Epoch 38  (lr = 1e-05)        Loss: 0.1822 - 1.6137 - WA: 66.07% <71.63%> - UA: 70.48% <74.16%>


100%|██████████| 19/19 [00:02<00:00,  6.42it/s]


 ang  sad  hap  neu
  61    4   12    5
   3   96    6   11
   0   14  115   17
   4   53   52  104
36 38
Epoch 39  (lr = 1e-05)        Loss: 0.1893 - 1.6521 - WA: 67.50% <71.63%> - UA: 71.19% <74.16%>


100%|██████████| 19/19 [00:02<00:00,  6.41it/s]


 ang  sad  hap  neu
  62    4   12    4
   4   97    6    9
   1   11  121   13
   4   39   63  107
36 39
Epoch 40  (lr = 1e-05)        Loss: 0.1739 - 1.6641 - WA: 69.48% <71.63%> - UA: 73.09% <74.16%>


100%|██████████| 19/19 [00:02<00:00,  6.41it/s]


 ang  sad  hap  neu
  58    5   15    4
   2   99    4   11
   2   13  109   22
   5   41   44  123
36 40
Epoch 41  (lr = 1e-05)        Loss: 0.1704 - 1.5148 - WA: 69.84% <71.63%> - UA: 72.12% <74.16%>


100%|██████████| 19/19 [00:02<00:00,  6.38it/s]


 ang  sad  hap  neu
  66    3    7    6
   3  105    3    5
   7   17  101   21
   9   62   37  105
36 41
Epoch 42  (lr = 1e-05)        Loss: 0.1733 - 1.5534 - WA: 67.68% <71.63%> - UA: 72.37% <74.16%>


100%|██████████| 19/19 [00:02<00:00,  6.40it/s]


 ang  sad  hap  neu
  63    4    7    8
   3  103    4    6
   2   14  104   26
   6   51   36  120
36 42
Epoch 43  (lr = 1e-05)        Loss: 0.1719 - 1.4473 - WA: 70.02% <71.63%> - UA: 73.30% <74.16%>


100%|██████████| 19/19 [00:02<00:00,  6.40it/s]


 ang  sad  hap  neu
  64    3    9    6
   4   99    5    8
   3    9  120   14
   6   48   49  110
36 43
Epoch 44  (lr = 1e-05)        Loss: 0.1637 - 1.4617 - WA: 70.56% <71.63%> - UA: 74.31% <74.16%>


100%|██████████| 19/19 [00:02<00:00,  6.40it/s]


 ang  sad  hap  neu
  62    3   13    4
   4  103    3    6
   2   11  113   20
   9   42   48  114
36 44
Epoch 45  (lr = 1e-05)        Loss: 0.1480 - 1.5265 - WA: 70.38% <71.63%> - UA: 73.83% <74.16%>


100%|██████████| 19/19 [00:02<00:00,  6.40it/s]


 ang  sad  hap  neu
  65    4    7    6
   4  106    1    5
   3   14  100   29
   5   48   31  129
True
45 45
Epoch 46  (lr = 1e-05)        Loss: 0.1436 - 1.6582 - WA: 71.81% <71.81%> - UA: 74.93% <74.93%>


100%|██████████| 19/19 [00:02<00:00,  6.41it/s]


 ang  sad  hap  neu
  67    3    3    9
   4  103    1    8
   7   16   87   36
   8   47   23  135
45 46
Epoch 47  (lr = 1e-05)        Loss: 0.1406 - 1.4351 - WA: 70.38% <71.81%> - UA: 73.37% <74.93%>


100%|██████████| 19/19 [00:02<00:00,  6.41it/s]


 ang  sad  hap  neu
  62    4   11    5
   4  105    3    4
   2   17  106   21
   3   62   47  101
45 47
Epoch 48  (lr = 1e-05)        Loss: 0.1304 - 1.7357 - WA: 67.15% <71.81%> - UA: 71.54% <74.93%>


100%|██████████| 19/19 [00:02<00:00,  6.40it/s]


 ang  sad  hap  neu
  61    6   11    4
   3  102    5    6
   2   15  109   20
   5   67   39  102
45 48
Epoch 49  (lr = 1e-05)        Loss: 0.1320 - 1.7421 - WA: 67.15% <71.81%> - UA: 71.22% <74.93%>


100%|██████████| 19/19 [00:02<00:00,  6.40it/s]


 ang  sad  hap  neu
  67    4    8    3
   3  104    4    5
   6   14  110   16
  10   54   47  102
45 49
Epoch 50  (lr = 1e-05)        Loss: 0.1468 - 1.4947 - WA: 68.76% <71.81%> - UA: 73.65% <74.93%>


100%|██████████| 17/17 [00:02<00:00,  6.54it/s]


 ang  sad  hap  neu
 112    2    9   24
   1   62    8    7
  13    7   95   17
   5   49   27   90
 ang  sad  hap  neu
 112    2    9   24
   1   62    8    7
  13    7   95   17
   5   49   27   90
****************************************
RESULTS ON TEST SET:
Loss:1.9917	WA: 67.99	UA: 70.07
Confusion matrix:
 ang  sad  hap  neu
 112    2    9   24
   1   62    8    7
  13    7   95   17
   5   49   27   90
****************************************

PARAMETERS:

****************************************


       ser_task: SLM
     repeat_idx: 0
         val_id: 2M
        test_id: 2F
     num_epochs: 50
     early_stop: 10
     batch_size: 32
             lr: 1e-05
    random_seed: 111
        use_gpu: 1
        gpu_ids: ['0']
     save_label: 2024-10-20-15-22
   oversampling: False
     pretrained: True
****************************************



Dataset normalized with minmax scaler
	Range before normalization: [-80.0, 3.8146973e-06]
	Range after  normalization: [0.0, 1.0]

<<DATASET>

/home/stud1/.local/lib/python3.10/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/stud1/.local/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)



<< SER AlexNet Finetuning model initialized >>



/home/stud1/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py:1142: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Some weights of Wav2Vec2Model were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original1', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Ser_Model(
  (alexnet_model): SER_AlexNet(
    (features): Sequential(
      (0): Conv2d(3, 64, kernel_size=(11, 11), stride=(4, 4), padding=(2, 2))
      (1): ReLU(inplace=True)
      (2): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
      (3): Conv2d(64, 192, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
      (4): ReLU(inplace=True)
      (5): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
      (6): Conv2d(192, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (7): ReLU(inplace=True)
      (8): Conv2d(384, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (9): ReLU(inplace=True)
      (10): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (11): ReLU(inplace=True)
      (12): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    )
    (avgpool): AdaptiveAvgPool2d(output_size=(6, 6))
    (classifier): Sequential(
      (0): Dropout(p=0.5, inplace=Fa

100%|██████████| 19/19 [00:02<00:00,  6.36it/s]


 ang  sad  hap  neu
  20    1   38   11
   0   60    2   22
   5   11   76   69
   4   38   66  119
True
0 0
Epoch 1  (lr = 1e-05)        Loss: 1.2500 - 1.1034 - WA: 50.74% <50.74%> - UA: 49.91% <49.91%>


100%|██████████| 19/19 [00:02<00:00,  6.36it/s]


 ang  sad  hap  neu
  28    0   22   20
   0   57    1   26
   9   10   71   71
   7   25   37  158
True
1 1
Epoch 2  (lr = 1e-05)        Loss: 1.0870 - 1.0317 - WA: 57.93% <57.93%> - UA: 55.39% <55.39%>


100%|██████████| 19/19 [00:02<00:00,  6.34it/s]


 ang  sad  hap  neu
  52    0    9    9
   1   53    2   28
  26    3   89   43
  17   23   59  128
True
2 2
Epoch 3  (lr = 1e-05)        Loss: 1.0130 - 1.0149 - WA: 59.41% <59.41%> - UA: 62.26% <62.26%>


100%|██████████| 19/19 [00:02<00:00,  6.35it/s]


 ang  sad  hap  neu
  54    0   11    5
   0   69    3   12
  14   13  108   26
  17   30   64  116
True
3 3
Epoch 4  (lr = 1e-05)        Loss: 0.9624 - 0.9949 - WA: 64.02% <64.02%> - UA: 69.37% <69.37%>


100%|██████████| 19/19 [00:02<00:00,  6.35it/s]


 ang  sad  hap  neu
  52    0   11    7
   0   71    1   12
  15   15  112   19
  11   33   73  110
3 4
Epoch 5  (lr = 1e-05)        Loss: 0.9148 - 1.0028 - WA: 63.65% <64.02%> - UA: 69.21% <69.37%>


100%|██████████| 19/19 [00:02<00:00,  6.34it/s]


 ang  sad  hap  neu
  53    0   10    7
   0   75    2    7
  15   19  108   19
  15   43   74   95
3 5
Epoch 6  (lr = 1e-05)        Loss: 0.8730 - 1.0293 - WA: 61.07% <64.02%> - UA: 68.48% <69.37%>


100%|██████████| 19/19 [00:02<00:00,  6.35it/s]


 ang  sad  hap  neu
  65    0    3    2
   0   57    6   21
  23    7  106   25
  29   23   64  111
3 6
Epoch 7  (lr = 1e-05)        Loss: 0.8301 - 1.0120 - WA: 62.55% <64.02%> - UA: 68.86% <69.37%>


100%|██████████| 19/19 [00:02<00:00,  6.35it/s]


 ang  sad  hap  neu
  66    0    3    1
   1   66    2   15
  25    7  112   17
  35   27   61  104
True
7 7
Epoch 8  (lr = 1e-05)        Loss: 0.7950 - 1.0463 - WA: 64.21% <64.21%> - UA: 72.06% <72.06%>


100%|██████████| 19/19 [00:02<00:00,  6.35it/s]


 ang  sad  hap  neu
  58    0   11    1
   0   74    5    5
  10   11  132    8
  11   32  109   75
7 8
Epoch 9  (lr = 1e-05)        Loss: 0.7500 - 1.0579 - WA: 62.55% <64.21%> - UA: 71.49% <72.06%>


100%|██████████| 19/19 [00:02<00:00,  6.37it/s]


 ang  sad  hap  neu
  58    0   11    1
   1   70    9    4
   8    8  138    7
  14   24  115   74
7 9
Epoch 10  (lr = 1e-05)        Loss: 0.7109 - 1.0403 - WA: 62.73% <64.21%> - UA: 71.13% <72.06%>


100%|██████████| 19/19 [00:02<00:00,  6.34it/s]


 ang  sad  hap  neu
  55    0   13    2
   0   76    4    4
   8   11  133    9
   6   29  109   83
7 10
Epoch 11  (lr = 1e-05)        Loss: 0.6767 - 1.0464 - WA: 64.02% <64.21%> - UA: 72.06% <72.06%>


100%|██████████| 19/19 [00:02<00:00,  6.34it/s]


 ang  sad  hap  neu
  60    0    8    2
   0   69   11    4
  10    6  137    8
  12   21  117   77
7 11
Epoch 12  (lr = 1e-05)        Loss: 0.6349 - 1.1609 - WA: 63.28% <64.21%> - UA: 71.72% <72.06%>


100%|██████████| 19/19 [00:02<00:00,  6.36it/s]


 ang  sad  hap  neu
  63    0    7    0
   1   62    5   16
  13    3  133   12
  15   18   76  118
True
12 12
Epoch 13  (lr = 1e-05)        Loss: 0.6182 - 1.0451 - WA: 69.37% <69.37%> - UA: 74.60% <74.60%>


100%|██████████| 19/19 [00:02<00:00,  6.34it/s]


 ang  sad  hap  neu
  65    0    3    2
   2   64    6   12
  10    5  133   13
  11   21   72  123
True
13 13
Epoch 14  (lr = 1e-05)        Loss: 0.5793 - 1.0671 - WA: 71.03% <71.03%> - UA: 76.46% <76.46%>


100%|██████████| 19/19 [00:02<00:00,  6.36it/s]


 ang  sad  hap  neu
  65    0    3    2
   1   70    0   13
  14    8  111   28
  13   27   37  150
True
14 14
Epoch 15  (lr = 1e-05)        Loss: 0.5677 - 0.9134 - WA: 73.06% <73.06%> - UA: 77.80% <77.80%>


100%|██████████| 19/19 [00:02<00:00,  6.36it/s]


 ang  sad  hap  neu
  65    0    3    2
   1   60    6   17
  16    3  129   13
  14   16   64  133
14 15
Epoch 16  (lr = 1e-05)        Loss: 0.5395 - 1.0674 - WA: 71.40% <73.06%> - UA: 75.75% <77.80%>


100%|██████████| 19/19 [00:02<00:00,  6.33it/s]


 ang  sad  hap  neu
  64    0    3    3
   1   66    5   12
  11    8  115   27
  12   22   47  146
14 16
Epoch 17  (lr = 1e-05)        Loss: 0.5120 - 1.0005 - WA: 72.14% <73.06%> - UA: 76.44% <77.80%>


100%|██████████| 19/19 [00:02<00:00,  6.36it/s]


 ang  sad  hap  neu
  62    1    3    4
   1   75    4    4
   9   13  113   26
   7   30   48  142
14 17
Epoch 18  (lr = 1e-05)        Loss: 0.4831 - 1.0966 - WA: 72.32% <73.06%> - UA: 77.65% <77.80%>


100%|██████████| 19/19 [00:02<00:00,  6.35it/s]


 ang  sad  hap  neu
  57    0   11    2
   0   72    8    4
   4    5  145    7
   7   29  100   91
14 18
Epoch 19  (lr = 1e-05)        Loss: 0.4620 - 1.3170 - WA: 67.34% <73.06%> - UA: 74.32% <77.80%>


100%|██████████| 19/19 [00:02<00:00,  6.35it/s]


 ang  sad  hap  neu
  65    0    3    2
   2   63    7   12
  11    5  125   20
  15   19   48  145
14 19
Epoch 20  (lr = 1e-05)        Loss: 0.4414 - 1.1102 - WA: 73.43% <73.06%> - UA: 77.34% <77.80%>


100%|██████████| 19/19 [00:02<00:00,  6.37it/s]


 ang  sad  hap  neu
  66    0    3    1
   2   66    8    8
  13    4  134   10
  22   19   85  101
14 20
Epoch 21  (lr = 1e-05)        Loss: 0.4141 - 1.3666 - WA: 67.71% <73.06%> - UA: 75.15% <77.80%>


100%|██████████| 19/19 [00:02<00:00,  6.37it/s]


 ang  sad  hap  neu
  64    0    2    4
   2   74    1    7
   8    9  120   24
  16   36   41  134
14 21
Epoch 22  (lr = 1e-05)        Loss: 0.4204 - 1.1991 - WA: 72.32% <73.06%> - UA: 78.27% <77.80%>


100%|██████████| 19/19 [00:02<00:00,  6.34it/s]


 ang  sad  hap  neu
  64    0    5    1
   1   63    5   15
   7    4  136   14
  12   20   72  123
14 22
Epoch 23  (lr = 1e-05)        Loss: 0.3649 - 1.2130 - WA: 71.22% <73.06%> - UA: 76.27% <77.80%>


100%|██████████| 19/19 [00:02<00:00,  6.34it/s]


 ang  sad  hap  neu
  65    0    2    3
   2   70    4    8
  11    5  126   19
  15   21   56  135
True
23 23
Epoch 24  (lr = 1e-05)        Loss: 0.3664 - 1.2907 - WA: 73.06% <73.06%> - UA: 78.48% <78.48%>


100%|██████████| 19/19 [00:03<00:00,  6.33it/s]


 ang  sad  hap  neu
  66    0    3    1
   2   54   17   11
  11    4  134   12
  20   14   71  122
23 24
Epoch 25  (lr = 1e-05)        Loss: 0.3383 - 1.4952 - WA: 69.37% <73.06%> - UA: 73.89% <78.48%>


100%|██████████| 19/19 [00:03<00:00,  6.32it/s]


 ang  sad  hap  neu
  61    0    5    4
   1   61    5   17
   5    4  133   19
   9   16   55  147
23 25
Epoch 26  (lr = 1e-05)        Loss: 0.3404 - 1.2870 - WA: 74.17% <73.06%> - UA: 76.78% <78.48%>


100%|██████████| 19/19 [00:02<00:00,  6.36it/s]


 ang  sad  hap  neu
  64    0    2    4
   2   71    5    6
   8    6  134   13
  15   27   69  116
23 26
Epoch 27  (lr = 1e-05)        Loss: 0.3230 - 1.4445 - WA: 71.03% <73.06%> - UA: 77.57% <78.48%>


100%|██████████| 19/19 [00:02<00:00,  6.34it/s]


 ang  sad  hap  neu
  67    0    3    0
   2   68    6    8
  13    5  132   11
  25   17   76  109
23 27
Epoch 28  (lr = 1e-05)        Loss: 0.3036 - 1.5937 - WA: 69.37% <73.06%> - UA: 76.67% <78.48%>


100%|██████████| 19/19 [00:03<00:00,  6.33it/s]


 ang  sad  hap  neu
  53    0   14    3
   1   67    8    8
   2    4  144   11
   8   19   92  108
23 28
Epoch 29  (lr = 1e-05)        Loss: 0.2966 - 1.5672 - WA: 68.63% <73.06%> - UA: 73.12% <78.48%>


100%|██████████| 19/19 [00:03<00:00,  6.32it/s]


 ang  sad  hap  neu
  63    0    7    0
   2   66    6   10
   9    6  134   12
  11   21   71  124
23 29
Epoch 30  (lr = 1e-05)        Loss: 0.2974 - 1.4058 - WA: 71.40% <73.06%> - UA: 76.61% <78.48%>


100%|██████████| 19/19 [00:02<00:00,  6.34it/s]


 ang  sad  hap  neu
  66    0    3    1
   1   68    7    8
  12    7  122   20
  16   26   52  133
23 30
Epoch 31  (lr = 1e-05)        Loss: 0.2772 - 1.5273 - WA: 71.77% <73.06%> - UA: 77.40% <78.48%>


100%|██████████| 19/19 [00:03<00:00,  6.33it/s]


 ang  sad  hap  neu
  57    1   11    1
   1   67   10    6
   4    7  141    9
   9   24   93  101
23 31
Epoch 32  (lr = 1e-05)        Loss: 0.2663 - 1.5928 - WA: 67.53% <73.06%> - UA: 73.32% <78.48%>


100%|██████████| 19/19 [00:02<00:00,  6.34it/s]


 ang  sad  hap  neu
  66    0    4    0
   2   64    6   12
  14    5  126   16
  14   18   69  126
23 32
Epoch 33  (lr = 1e-05)        Loss: 0.2422 - 1.6095 - WA: 70.48% <73.06%> - UA: 76.06% <78.48%>


100%|██████████| 19/19 [00:03<00:00,  6.33it/s]


 ang  sad  hap  neu
  64    0    4    2
   2   62    9   11
   7    4  133   17
   9   15   64  139
23 33
Epoch 34  (lr = 1e-05)        Loss: 0.2451 - 1.4594 - WA: 73.43% <73.06%> - UA: 77.27% <78.48%>


100%|██████████| 15/15 [00:02<00:00,  6.44it/s]


 ang  sad  hap  neu
  56    1    4    6
   2   75   23   13
   4    5  142   15
   5   17   37   76
 ang  sad  hap  neu
  56    1    4    6
   2   75   23   13
   4    5  142   15
   5   17   37   76
****************************************
RESULTS ON TEST SET:
Loss:1.1591	WA: 72.56	UA: 72.95
Confusion matrix:
 ang  sad  hap  neu
  56    1    4    6
   2   75   23   13
   4    5  142   15
   5   17   37   76
****************************************

PARAMETERS:

****************************************


       ser_task: SLM
     repeat_idx: 0
         val_id: 3M
        test_id: 3F
     num_epochs: 50
     early_stop: 10
     batch_size: 32
             lr: 1e-05
    random_seed: 111
        use_gpu: 1
        gpu_ids: ['0']
     save_label: 2024-10-20-15-22
   oversampling: False
     pretrained: True
****************************************



Dataset normalized with minmax scaler
	Range before normalization: [-80.0, 3.8146973e-06]
	Range after  normalization: [0.0, 1.0]

<<DATASET>

/home/stud1/.local/lib/python3.10/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/stud1/.local/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)



<< SER AlexNet Finetuning model initialized >>



/home/stud1/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py:1142: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Some weights of Wav2Vec2Model were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original1', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Ser_Model(
  (alexnet_model): SER_AlexNet(
    (features): Sequential(
      (0): Conv2d(3, 64, kernel_size=(11, 11), stride=(4, 4), padding=(2, 2))
      (1): ReLU(inplace=True)
      (2): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
      (3): Conv2d(64, 192, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
      (4): ReLU(inplace=True)
      (5): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
      (6): Conv2d(192, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (7): ReLU(inplace=True)
      (8): Conv2d(384, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (9): ReLU(inplace=True)
      (10): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (11): ReLU(inplace=True)
      (12): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    )
    (avgpool): AdaptiveAvgPool2d(output_size=(6, 6))
    (classifier): Sequential(
      (0): Dropout(p=0.5, inplace=Fa

100%|██████████| 20/20 [00:03<00:00,  6.17it/s]


 ang  sad  hap  neu
  76    6   46   20
   1  103    7   22
  23   29   75   31
   4   59   54   73
True
0 0
Epoch 1  (lr = 1e-05)        Loss: 1.2549 - 1.1184 - WA: 51.99% <51.99%> - UA: 53.67% <53.67%>


100%|██████████| 20/20 [00:03<00:00,  6.18it/s]


 ang  sad  hap  neu
  88    5   24   31
   1  104    2   26
  22   35   58   43
   7   66   16  101
True
1 1
Epoch 2  (lr = 1e-05)        Loss: 1.0584 - 1.1039 - WA: 55.80% <55.80%> - UA: 56.88% <56.88%>


100%|██████████| 20/20 [00:03<00:00,  6.17it/s]


 ang  sad  hap  neu
  84   15   22   27
   0  121    2   10
  17   48   61   32
   7   92   19   72
1 2
Epoch 3  (lr = 1e-05)        Loss: 0.9950 - 1.0973 - WA: 53.74% <55.80%> - UA: 56.06% <56.88%>


100%|██████████| 20/20 [00:03<00:00,  6.19it/s]


 ang  sad  hap  neu
  92   15   15   26
   0  117    2   14
  20   43   57   38
  11   82   16   81
1 3
Epoch 4  (lr = 1e-05)        Loss: 0.9323 - 1.0928 - WA: 55.17% <55.80%> - UA: 57.21% <56.88%>


100%|██████████| 20/20 [00:03<00:00,  6.18it/s]


 ang  sad  hap  neu
 107   15    6   20
   2  122    0    9
  41   51   37   29
  26   80    4   80
1 4
Epoch 5  (lr = 1e-05)        Loss: 0.8941 - 1.1252 - WA: 55.01% <55.80%> - UA: 57.39% <56.88%>


100%|██████████| 20/20 [00:03<00:00,  6.16it/s]


 ang  sad  hap  neu
  93    9   15   31
   2  115    0   16
  15   42   54   47
  12   55    6  117
True
5 5
Epoch 6  (lr = 1e-05)        Loss: 0.8544 - 1.0643 - WA: 60.25% <60.25%> - UA: 61.27% <61.27%>


100%|██████████| 20/20 [00:03<00:00,  6.18it/s]


 ang  sad  hap  neu
 100   11   19   18
   2  116    3   12
  14   35   92   17
  20   50   27   93
True
6 6
Epoch 7  (lr = 1e-05)        Loss: 0.7979 - 0.9606 - WA: 63.75% <63.75%> - UA: 65.49% <65.49%>


100%|██████████| 20/20 [00:03<00:00,  6.17it/s]


 ang  sad  hap  neu
 106    9    8   25
   2  112    0   19
  31   38   48   41
  25   44    2  119
6 7
Epoch 8  (lr = 1e-05)        Loss: 0.7560 - 1.0268 - WA: 61.21% <63.75%> - UA: 62.21% <65.49%>


100%|██████████| 20/20 [00:03<00:00,  6.17it/s]


 ang  sad  hap  neu
 100   15   18   15
   1  125    2    5
  16   44   80   18
  19   65   22   84
6 8
Epoch 9  (lr = 1e-05)        Loss: 0.7220 - 0.9969 - WA: 61.84% <63.75%> - UA: 64.10% <65.49%>


100%|██████████| 20/20 [00:03<00:00,  6.13it/s]


 ang  sad  hap  neu
 108    7   16   17
   1  112    6   14
  16   29   90   23
  15   40   30  105
True
9 9
Epoch 10  (lr = 1e-05)        Loss: 0.6832 - 0.9366 - WA: 65.98% <65.98%> - UA: 67.35% <67.35%>


100%|██████████| 20/20 [00:03<00:00,  6.16it/s]


 ang  sad  hap  neu
 105    5   10   28
   2  114    0   17
  17   31   75   35
  15   46   11  118
9 10
Epoch 11  (lr = 1e-05)        Loss: 0.6401 - 1.0082 - WA: 65.50% <65.98%> - UA: 66.56% <67.35%>


100%|██████████| 20/20 [00:03<00:00,  6.18it/s]


 ang  sad  hap  neu
 110    6   14   18
   2  117    2   12
  21   32   81   24
  20   45   15  110
True
11 11
Epoch 12  (lr = 1e-05)        Loss: 0.6009 - 1.0371 - WA: 66.45% <66.45%> - UA: 67.86% <67.86%>


100%|██████████| 20/20 [00:03<00:00,  6.18it/s]


 ang  sad  hap  neu
 103   11   17   17
   1  125    2    5
  15   38   84   21
  11   58   16  105
11 12
Epoch 13  (lr = 1e-05)        Loss: 0.5811 - 0.9961 - WA: 66.30% <66.45%> - UA: 68.00% <67.86%>


100%|██████████| 20/20 [00:03<00:00,  6.15it/s]


 ang  sad  hap  neu
 108   11    9   20
   1  118    1   13
  17   36   73   32
  13   51    6  120
True
13 13
Epoch 14  (lr = 1e-05)        Loss: 0.5350 - 1.0423 - WA: 66.61% <66.61%> - UA: 67.76% <67.76%>


100%|██████████| 20/20 [00:03<00:00,  6.16it/s]


 ang  sad  hap  neu
 100    7   16   25
   1  115    4   13
   9   32   87   30
   7   44   19  120
True
14 14
Epoch 15  (lr = 1e-05)        Loss: 0.5142 - 1.0447 - WA: 67.09% <67.09%> - UA: 68.06% <68.06%>


100%|██████████| 20/20 [00:03<00:00,  6.15it/s]


 ang  sad  hap  neu
 105    3   27   13
   2  118    7    6
  14   23  109   12
  19   45   37   89
True
15 15
Epoch 16  (lr = 1e-05)        Loss: 0.4918 - 1.0464 - WA: 66.93% <66.93%> - UA: 68.87% <68.87%>


100%|██████████| 20/20 [00:03<00:00,  6.19it/s]


 ang  sad  hap  neu
 101    3   25   19
   2  111    4   16
  10   25  104   19
  12   35   28  115
True
16 16
Epoch 17  (lr = 1e-05)        Loss: 0.4641 - 1.0813 - WA: 68.52% <68.52%> - UA: 69.51% <69.51%>


100%|██████████| 20/20 [00:03<00:00,  6.16it/s]


 ang  sad  hap  neu
 103    8   14   23
   1  111    2   19
  12   35   80   31
   9   43    9  129
16 17
Epoch 18  (lr = 1e-05)        Loss: 0.4394 - 1.1589 - WA: 67.25% <68.52%> - UA: 67.90% <69.51%>


100%|██████████| 20/20 [00:03<00:00,  6.16it/s]


 ang  sad  hap  neu
 101    5   20   22
   1  111    6   15
  10   32  101   15
  10   47   28  105
16 18
Epoch 19  (lr = 1e-05)        Loss: 0.4193 - 1.0925 - WA: 66.45% <68.52%> - UA: 67.72% <69.51%>


100%|██████████| 20/20 [00:03<00:00,  6.18it/s]


 ang  sad  hap  neu
 103    0   21   24
   3   95    4   31
   9   17  110   22
  14   22   25  129
True
19 19
Epoch 20  (lr = 1e-05)        Loss: 0.3956 - 1.1843 - WA: 69.48% <69.48%> - UA: 69.63% <69.63%>


100%|██████████| 20/20 [00:03<00:00,  6.18it/s]


 ang  sad  hap  neu
  99    1   19   29
   2  101    4   26
  11   20   95   32
  10   29   10  141
19 20
Epoch 21  (lr = 1e-05)        Loss: 0.3693 - 1.1582 - WA: 69.32% <69.48%> - UA: 69.29% <69.63%>


100%|██████████| 20/20 [00:03<00:00,  6.17it/s]


 ang  sad  hap  neu
 104    1   19   24
   2   89    6   36
  11   16  106   25
  13   23   19  135
19 21
Epoch 22  (lr = 1e-05)        Loss: 0.3581 - 1.2003 - WA: 69.00% <69.48%> - UA: 68.83% <69.63%>


100%|██████████| 20/20 [00:03<00:00,  6.17it/s]


 ang  sad  hap  neu
 103   11   17   17
   2  119    6    6
  13   29   99   17
  12   50   25  103
19 22
Epoch 23  (lr = 1e-05)        Loss: 0.3438 - 1.2576 - WA: 67.41% <69.48%> - UA: 68.98% <69.63%>


100%|██████████| 20/20 [00:03<00:00,  6.03it/s]


 ang  sad  hap  neu
  93    2   28   25
   3  103    6   21
   7   23  108   20
  11   36   19  124
19 23
Epoch 24  (lr = 1e-05)        Loss: 0.3229 - 1.2875 - WA: 68.04% <69.48%> - UA: 68.47% <69.63%>


100%|██████████| 20/20 [00:03<00:00,  6.16it/s]


 ang  sad  hap  neu
 101    0   20   27
   2   93    8   30
  10   12  112   24
   8   24   22  136
True
24 24
Epoch 25  (lr = 1e-05)        Loss: 0.3003 - 1.2563 - WA: 70.27% <70.27%> - UA: 70.16% <70.16%>


100%|██████████| 20/20 [00:03<00:00,  6.17it/s]


 ang  sad  hap  neu
  99    9   27   13
   2  113   10    8
  10   25  114    9
  10   44   43   93
24 25
Epoch 26  (lr = 1e-05)        Loss: 0.3095 - 1.2244 - WA: 66.61% <70.27%> - UA: 68.24% <70.16%>


100%|██████████| 20/20 [00:03<00:00,  6.16it/s]


 ang  sad  hap  neu
 107    2   15   24
   2  103    4   24
   8   16  109   25
  11   29   19  131
True
26 26
Epoch 27  (lr = 1e-05)        Loss: 0.2734 - 1.2847 - WA: 71.54% <71.54%> - UA: 71.92% <71.92%>


100%|██████████| 20/20 [00:03<00:00,  6.14it/s]


 ang  sad  hap  neu
  95    6   23   24
   2   99    4   28
   8   19  100   31
   7   29   15  139
26 27
Epoch 28  (lr = 1e-05)        Loss: 0.2740 - 1.4003 - WA: 68.84% <71.54%> - UA: 68.77% <71.92%>


100%|██████████| 20/20 [00:03<00:00,  6.16it/s]


 ang  sad  hap  neu
 105    1   20   22
   3  101    9   20
  11   15  110   22
  11   27   21  131
26 28
Epoch 29  (lr = 1e-05)        Loss: 0.2634 - 1.3145 - WA: 71.07% <71.54%> - UA: 71.36% <71.92%>


100%|██████████| 20/20 [00:03<00:00,  6.17it/s]


 ang  sad  hap  neu
  98    6   22   22
   2  111    5   15
   7   23  111   17
   9   42   22  117
26 29
Epoch 30  (lr = 1e-05)        Loss: 0.2475 - 1.3004 - WA: 69.48% <71.54%> - UA: 70.38% <71.92%>


100%|██████████| 20/20 [00:03<00:00,  6.16it/s]


 ang  sad  hap  neu
  98    1   28   21
   2  100    9   22
   5   17  122   14
  10   33   35  112
26 30
Epoch 31  (lr = 1e-05)        Loss: 0.2460 - 1.2974 - WA: 68.68% <71.54%> - UA: 69.39% <71.92%>


100%|██████████| 20/20 [00:03<00:00,  6.18it/s]


 ang  sad  hap  neu
 111    1   18   18
   3  109    8   13
  15   20  109   14
  16   34   25  115
26 31
Epoch 32  (lr = 1e-05)        Loss: 0.2281 - 1.3558 - WA: 70.59% <71.54%> - UA: 71.62% <71.92%>


 86%|████████▌ | 235/274 [00:57<00:09,  4.12it/s]


KeyboardInterrupt: 

In [1]:
import numpy as np

# Confusion matrices
matrix_1 = np.array([
    [112, 2, 9, 24],
    [1, 62, 8, 7],
    [13, 7, 95, 17],
    [5, 49, 27, 90]
])

matrix_2 = np.array([
    [56, 1, 4, 6],
    [2, 75, 23, 13],
    [4, 5, 142, 15],
    [5, 17, 37, 76]
])

# Normalizing the rows by dividing each element by the row sum
def normalize(matrix):
    return matrix / matrix.sum(axis=1, keepdims=True)

# Normalize both matrices
normalized_matrix_1 = normalize(matrix_1)
normalized_matrix_2 = normalize(matrix_2)

# Compute the element-wise average of the two normalized matrices
averaged_matrix = (normalized_matrix_1 + normalized_matrix_2) / 2

# Output the results
print("Normalized Matrix 1:")
print(normalized_matrix_1)

print("\nNormalized Matrix 2:")
print(normalized_matrix_2)

print("\nAveraged Confusion Matrix:")
print(averaged_matrix)

Normalized Matrix 1:
[[0.76190476 0.01360544 0.06122449 0.16326531]
 [0.01282051 0.79487179 0.1025641  0.08974359]
 [0.09848485 0.0530303  0.71969697 0.12878788]
 [0.02923977 0.28654971 0.15789474 0.52631579]]

Normalized Matrix 2:
[[0.8358209  0.01492537 0.05970149 0.08955224]
 [0.01769912 0.66371681 0.20353982 0.11504425]
 [0.02409639 0.03012048 0.85542169 0.09036145]
 [0.03703704 0.12592593 0.27407407 0.56296296]]

Averaged Confusion Matrix:
[[0.79886283 0.01426541 0.06046299 0.12640877]
 [0.01525981 0.7292943  0.15305196 0.10239392]
 [0.06129062 0.04157539 0.78755933 0.10957466]
 [0.0331384  0.20623782 0.21598441 0.54463938]]
